function readEnv(name, fallback = '') {
  const value = process.env[name];

  if (typeof value !== 'string') {
    return fallback;
  }

  return value.trim();
}

const defaultTrierExtensionRepoUrl =
  'https://github.com/UnicoContato/trier_extensao.git';
const defaultTrierExtensionRepoBranch = 'main';
const defaultInovaFarmaExtensionRepoUrl =
  'https://github.com/UnicoContato/Extensao_inova_revisada.git';
const defaultInovaFarmaExtensionRepoBranch = 'main';

export const env = {
  PORT: Number(readEnv('PORT', '4000')),
  HOST: readEnv('HOST', '127.0.0.1'),
  INSTANCE_SERVICE_USERNAME: readEnv('INSTANCE_SERVICE_USERNAME'),
  INSTANCE_SERVICE_PASSWORD: readEnv('INSTANCE_SERVICE_PASSWORD'),
  INSTANCE_SERVICE_TOTP_SECRET: readEnv('INSTANCE_SERVICE_TOTP_SECRET'),
  INSTANCE_SERVICE_TOTP_DIGITS: Number(readEnv('INSTANCE_SERVICE_TOTP_DIGITS', '6')),
  INSTANCE_SERVICE_TOTP_PERIOD_SECONDS: Number(
    readEnv('INSTANCE_SERVICE_TOTP_PERIOD_SECONDS', '30'),
  ),
  AI_URA_AUDIT_ENABLED: readEnv('AI_URA_AUDIT_ENABLED', 'true').toLowerCase() !== 'false',
  AI_URA_AUDIT_HOUR: Number(readEnv('AI_URA_AUDIT_HOUR', '3')),
  AI_URA_AUDIT_MINUTE: Number(readEnv('AI_URA_AUDIT_MINUTE', '0')),
  AI_URA_AUDIT_TIMEZONE: readEnv('AI_URA_AUDIT_TIMEZONE', 'America/Sao_Paulo'),
  OPENAI_API_KEY: readEnv('OPENAI_API_KEY'),
  OPENAI_MODEL: readEnv('OPENAI_MODEL', 'gpt-5.4'),
  OPENAI_REASONING_EFFORT: readEnv('OPENAI_REASONING_EFFORT', 'medium'),
  OPENAI_VERBOSITY: readEnv('OPENAI_VERBOSITY', 'medium'),
  TRIER_EXTENSION_REPO_URL:
    readEnv('TRIER_EXTENSION_REPO_URL', defaultTrierExtensionRepoUrl),
  TRIER_EXTENSION_REPO_BRANCH:
    readEnv('TRIER_EXTENSION_REPO_BRANCH', defaultTrierExtensionRepoBranch),
  TRIER_EXTENSION_TEMPLATE_DIR: readEnv('TRIER_EXTENSION_TEMPLATE_DIR'),
  TRIER_EXTENSION_TEMPLATE_ZIP: readEnv('TRIER_EXTENSION_TEMPLATE_ZIP'),
  INOVA_FARMA_EXTENSION_REPO_URL: readEnv(
    'INOVA_FARMA_EXTENSION_REPO_URL',
    defaultInovaFarmaExtensionRepoUrl,
  ),
  INOVA_FARMA_EXTENSION_REPO_BRANCH: readEnv(
    'INOVA_FARMA_EXTENSION_REPO_BRANCH',
    defaultInovaFarmaExtensionRepoBranch,
  ),
  INOVA_FARMA_EXTENSION_TEMPLATE_DIR: readEnv(
    'INOVA_FARMA_EXTENSION_TEMPLATE_DIR',
  ),
  INOVA_FARMA_EXTENSION_TEMPLATE_ZIP: readEnv(
    'INOVA_FARMA_EXTENSION_TEMPLATE_ZIP',
  ),
  MULTIPROVIDER_BASE_URL: readEnv('MULTIPROVIDER_BASE_URL'),
  MULTIPROVIDER_ADMIN_API_KEY: readEnv('MULTIPROVIDER_ADMIN_API_KEY'),
  BANCO_UNICO_BASE_URL: readEnv(
    'BANCO_UNICO_BASE_URL',
    'https://unicocontato.tech/banco-unico',
  ),
  BANCO_UNICO_AUTHORIZATION: readEnv('BANCO_UNICO_AUTHORIZATION'),
  HUBUNICO_BASE_URL: readEnv('HUBUNICO_BASE_URL'),
  HUBUNICO_ADMIN_API_KEY: readEnv('HUBUNICO_ADMIN_API_KEY'),
  UNICOMMERCE_BACK_BASE_URL: readEnv('UNICOMMERCE_BACK_BASE_URL'),
  UNICOMMERCE_BACK_INTERNAL_API_KEY: readEnv('UNICOMMERCE_BACK_INTERNAL_API_KEY'),
  CATALOG_DEPLOYMENT_ENVIRONMENT: readEnv('CATALOG_DEPLOYMENT_ENVIRONMENT', 'production').toLowerCase(),
  HUBUNICO_PRODUCTION_BASE_URL: readEnv('HUBUNICO_PRODUCTION_BASE_URL'),
  HUBUNICO_PRODUCTION_ADMIN_API_KEY: readEnv('HUBUNICO_PRODUCTION_ADMIN_API_KEY'),
  HUBUNICO_STAGING_BASE_URL: readEnv('HUBUNICO_STAGING_BASE_URL'),
  HUBUNICO_STAGING_ADMIN_API_KEY: readEnv('HUBUNICO_STAGING_ADMIN_API_KEY'),
  UNICOMMERCE_BACK_PRODUCTION_BASE_URL: readEnv('UNICOMMERCE_BACK_PRODUCTION_BASE_URL'),
  UNICOMMERCE_BACK_PRODUCTION_INTERNAL_API_KEY: readEnv('UNICOMMERCE_BACK_PRODUCTION_INTERNAL_API_KEY'),
  UNICOMMERCE_BACK_STAGING_BASE_URL: readEnv('UNICOMMERCE_BACK_STAGING_BASE_URL'),
  UNICOMMERCE_BACK_STAGING_INTERNAL_API_KEY: readEnv('UNICOMMERCE_BACK_STAGING_INTERNAL_API_KEY'),
  BANCO_UNICO_PRODUCTION_BASE_URL: readEnv('BANCO_UNICO_PRODUCTION_BASE_URL'),
  BANCO_UNICO_PRODUCTION_AUTHORIZATION: readEnv('BANCO_UNICO_PRODUCTION_AUTHORIZATION'),
  BANCO_UNICO_STAGING_BASE_URL: readEnv('BANCO_UNICO_STAGING_BASE_URL'),
  BANCO_UNICO_STAGING_AUTHORIZATION: readEnv('BANCO_UNICO_STAGING_AUTHORIZATION'),
  DEPLOYMENT_ENCRYPTION_KEY: readEnv('DEPLOYMENT_ENCRYPTION_KEY'),
  DEPLOYMENT_WORKER_ENABLED:
    readEnv('DEPLOYMENT_WORKER_ENABLED', 'true').toLowerCase() !== 'false',
  BANCO_UNICO_IMPORT_WORKER_ENABLED:
    readEnv('BANCO_UNICO_IMPORT_WORKER_ENABLED', 'true').toLowerCase() !== 'false',
  DEPLOYMENT_WORKER_INTERVAL_MS: Number(
    readEnv('DEPLOYMENT_WORKER_INTERVAL_MS', '5000'),
  ),
  DEPLOYMENT_LEASE_MS: Number(readEnv('DEPLOYMENT_LEASE_MS', '60000')),
  DEPLOYMENT_MONITOR_TIMEOUT_MS: Number(
    readEnv('DEPLOYMENT_MONITOR_TIMEOUT_MS', '1800000'),
  ),
  CORS_ALLOWED_ORIGINS: readEnv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://localhost:3000,https://unico-integra.vercel.app',
  )
    .split(',')
    .map((origin) => origin.trim())
    .filter(Boolean),
};
